### ISSUE TITLE
Broken Scrolling

### ISSUE THREAD

**Issue by jarulsamy** [calebegg/proof-pad#8]
After uploading a file, scrolling does not immediately render the next lines of text. If I manually click on a region, it appears, but the earlier regions disappear. 

This occurs on Linux and Windows with Firefox, Chrome, and the latest version of MS Edge. 
Is there any remedy for this? I have tried clearing cookies, and even trying brand new installations of web browsers, but I keep running into the same issues. 

![vid-demonstration](https://user-images.githubusercontent.com/14321139/95043244-7a817700-0699-11eb-911c-3bb6e7453855.gif)

**Comment by calebegg** [comment]
This should be fixed now -- thanks for the report!

**Comment by jarulsamy** [comment]
> This should be fixed now -- thanks for the report!

That was incredibly fast. Thanks so much!
